# content-based-recommendation-system

Use the "Run" button to execute the code.

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [101]:
data = pd.read_csv('Final_Employees_Data.csv')

In [102]:
data

,Eid,Ename,Experience,Total_projects,Rating,Area_of_Interest_1,Area_of_Interest_2,Area_of_Interest_3,Language1,Language2,Language3,AI_project_count,ML_project_count,JS_project_count,Java_project_count,DotNet_project_count,Mobile_project_count
0,1,Dana Bond,2,2,1.000000,DotNet,JS,AI,English,Hindi,Tamil,0,1,1,0,0,0
1,2,Jesus Hampton,9,13,1.444444,DotNet,AI,JS,English,Hindi,Malayalam,4,3,0,2,3,1
2,3,Teresa Munoz,15,16,1.066667,ML,JS,Java,English,Kannada,Chinese,3,3,1,3,5,1
3,4,Annette Dipietro,18,19,1.055556,DotNet,ML,Mobile,English,Chinese,Tamil,4,4,2,3,3,3
4,5,Jennifer Fortner,22,15,0.681818,Mobile,Java,JS,English,Chinese,Telugu,3,4,3,1,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Nicole Meeks,24,27,1.125000,Java,Mobile,AI,English,Telugu,Tamil,11,3,2,6,4,1
996,997,Trista Cheek,3,6,2.000000,Mobile,ML,DotNet,English,Chinese,Telugu,1,0,2,1,2,0
997,998,Constance Rozier,14,5,0.357143,AI,ML,Mobile,English,Kannada,Telugu,2,1,1,1,0,0
998,999,Elizabeth Bannister,11,9,0.818182,JS,ML,DotNet,English,Tamil,Japenese,4,2,1,1,0,1
999,1000,Susan Weber,11,13,1.181818,ML,AI,JS,English,Telugu,Hindi,4,0,1,2,5,1

In [103]:
data.describe()

,Eid,Experience,Total_projects,Rating,AI_project_count,ML_project_count,JS_project_count,Java_project_count,DotNet_project_count,Mobile_project_count
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,12.79900,14.692000,1.293804,2.845000,2.574000,2.597000,2.409000,2.228000,2.039000
std,288.819436,6.68111,7.443288,0.622976,1.978608,1.894231,2.011128,1.980313,1.836134,1.790163
min,1.000000,2.00000,2.000000,0.357143,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,250.750000,7.00000,8.000000,0.869565,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,500.500000,13.00000,15.000000,1.166667,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000
75%,750.250000,19.00000,20.000000,1.529412,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000
max,1000.000000,24.00000,29.000000,4.500000,11.000000,10.000000,11.000000,12.000000,9.000000,11.000000

In [104]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Eid                   1000 non-null   int64
 1   Ename                 1000 non-null   object
 2   Experience            1000 non-null   int64
 3   Total_projects        1000 non-null   int64
 4   Rating                1000 non-null   float64
 5   Area_of_Interest_1    1000 non-null   object
 6   Area_of_Interest_2    1000 non-null   object
 7   Area_of_Interest_3    1000 non-null   object
 8   Language1             1000 non-null   object
 9   Language2             1000 non-null   object
 10  Language3             1000 non-null   object
 11  AI_project_count      1000 non-null   int64
 12  ML_project_count      1000 non-null   int64
 13  JS_project_count      1000 non-null   int64
 14  Java_project_count    1000 non-null   int64
 15  DotNet_project_count  1000 non-null   int64
 16  Mobile_project_count  1000 non-null   int64
dtypes: float64(1), int64(9), object(7)
memory usage: 132.9+ KB

In [105]:
data.isnull().sum()

Eid                     0
Ename                   0
Experience              0
Total_projects          0
Rating                  0
Area_of_Interest_1      0
Area_of_Interest_2      0
Area_of_Interest_3      0
Language1               0
Language2               0
Language3               0
AI_project_count        0
ML_project_count        0
JS_project_count        0
Java_project_count      0
DotNet_project_count    0
Mobile_project_count    0
dtype: int64

In [106]:
data.duplicated().sum()

0

# Content Based recommendation system

## Required Feilds

In [114]:
data = pd.read_csv('Final_Employees_Data.csv')

In [115]:
data = data[['Eid', 'Ename', 'Experience', 'Total_projects', 'Area_of_Interest_1']]

In [116]:
data

      Eid                Ename  Experience  Total_projects Area_of_Interest_1
0       1            Dana Bond           2               2             DotNet
1       2        Jesus Hampton           9              13             DotNet
2       3         Teresa Munoz          15              16                 ML
3       4     Annette Dipietro          18              19             DotNet
4       5     Jennifer Fortner          22              15             Mobile
..    ...                  ...         ...             ...                ...
995   996         Nicole Meeks          24              27               Java
996   997         Trista Cheek           3               6             Mobile
997   998     Constance Rozier          14               5                 AI
998   999  Elizabeth Bannister          11               9                 JS
999  1000          Susan Weber          11              13                 ML

[1000 rows x 5 columns]

### Joim four coloumn for vectorization

In [74]:

data['Experience'] = pd.to_numeric(data['Experience'], errors='coerce')
data['Total_projects'] = pd.to_numeric(data['Total_projects'], errors='coerce')


data['newcolm'] = (data['Experience'] + data['Total_projects']).astype(str) + " " + data['Area_of_Interest_1']+" "+data['Ename']

/tmp/ipykernel_118/1412145984.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Experience'] = pd.to_numeric(data['Experience'], errors='coerce')
/tmp/ipykernel_118/1412145984.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Total_projects'] = pd.to_numeric(data['Total_projects'], errors='coerce')
/tmp/ipykernel_118/1412145984.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['newcolm'] = (data['Experience'] + data['Total_projects']).astype(str) + " " + data['Area_of_Interest_1']+" "+data['Ename']

In [75]:
data

,Eid,Ename,Experience,Total_projects,Area_of_Interest_1,newcolm
0,1,Dana Bond,2,2,DotNet,4 DotNet Dana Bond
1,2,Jesus Hampton,9,13,DotNet,22 DotNet Jesus Hampton
2,3,Teresa Munoz,15,16,ML,31 ML Teresa Munoz
3,4,Annette Dipietro,18,19,DotNet,37 DotNet Annette Dipietro
4,5,Jennifer Fortner,22,15,Mobile,37 Mobile Jennifer Fortner
...,...,...,...,...,...,...
995,996,Nicole Meeks,24,27,Java,51 Java Nicole Meeks
996,997,Trista Cheek,3,6,Mobile,9 Mobile Trista Cheek
997,998,Constance Rozier,14,5,AI,19 AI Constance Rozier
998,999,Elizabeth Bannister,11,9,JS,20 JS Elizabeth Bannister
999,1000,Susan Weber,11,13,ML,24 ML Susan Weber

### import vectorization and cosine similarity

In [117]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [77]:
tfif =TfidfVectorizer()
matrix = tfif.fit_transform(data['newcolm'])
similarity = cosine_similarity(matrix)

In [78]:
similarity

array([[1.        , 0.07203996, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.07203996, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.0615693 ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.0615693 , ..., 0.        , 0.        ,
        1.        ]])

In [79]:
similarity[0]

array([1.        , 0.07203996, 0.        , 0.07174857, 0.        ,
       0.        , 0.        , 0.07862399, 0.        , 0.        ,
       0.        , 0.07862399, 0.        , 0.        , 0.0703342 ,
       0.        , 0.        , 0.08043924, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07628054, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07220486, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07952659, 0.        , 0.07195285, 0.07097731, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07838027, 0.07861449,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07243171,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07039311, 0.        , 0.07880979, 0.        ,
       0.        , 0.07383086, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07409948, 0.07287261, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07420302, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07299944, 0.        ,
       0.        , 0.        , 0.        , 0.07022012, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07030834, 0.        , 0.07047467, 0.07047467,
       0.        , 0.        , 0.        , 0.07039311, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07671053, 0.        , 0.        ,
       0.        , 0.07509744, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06921334, 0.        , 0.        ,
       0.        , 0.        , 0.07971434, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07039311, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08008206, 0.        , 0.        , 0.08275072,
       0.07698746, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0673173 , 0.        ,
       0.07220486, 0.07287261, 0.07103278, 0.        , 0.        ,
       0.        , 0.        , 0.06971676, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07167001, 0.08426535,
       0.07037496, 0.07660161, 0.06947885, 0.        , 0.08216317,
       0.06947885, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07356689, 0.07857253, 0.        , 0.        ,
       0.        , 0.        , 0.07228304, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07332923, 0.        ,
       0.        , 0.08725925, 0.        , 0.07527046, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07952378, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07158697,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07176814, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0758443 , 0.        , 0.        , 0.06794107, 0.        ,
       0.        , 0.07341113, 0.        , 0.        , 0.        ,
       0.08216317, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.08020653,
       0.        , 0.        , 0.0721239 , 0.07638258, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07287889, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.36550617, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07579799, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06921334, 0.        , 0.        ,
       0.        , 0.        , 0.07682555, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07324443, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.08216317,
       0.07647648, 0.07186233, 0.07123061, 0.        , 0.06960092,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.08105488, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07620071, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06921334,
       0.        , 0.        , 0.        , 0.        , 0.07039311,
       0.        , 0.        , 0.        , 0.        , 0.07022012,
       0.        , 0.07240472, 0.        , 0.        , 0.07654472,
       0.        , 0.        , 0.        , 0.07454179, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07182614, 0.        , 0.        , 0.        ,
       0.        , 0.07134853, 0.        , 0.        , 0.07709559,
       0.07332923, 0.        , 0.        , 0.07030834, 0.07626911,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06947885, 0.        , 0.        , 0.07660161,
       0.        , 0.        , 0.        , 0.08008206, 0.        ,
       0.07342327, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07053972,
       0.07420588, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07356689, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07981631,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08216317, 0.        , 0.        , 0.        ,
       0.        , 0.07862399, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.06921334, 0.        ,
       0.        , 0.        , 0.        , 0.07550449, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.37163191,
       0.07975093, 0.07047467, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07479171,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07047467, 0.        , 0.        , 0.        ,
       0.        , 0.06921334, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07176814, 0.07186233,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07499489, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07862399, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07500429, 0.        , 0.        , 0.08104501,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.08008206, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08240144, 0.        , 0.        , 0.        , 0.36076564,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.06794107, 0.        ,
       0.        , 0.08344225, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07502068,
       0.07230981, 0.        , 0.        , 0.        , 0.        ,
       0.07156761, 0.        , 0.07765454, 0.07110746, 0.        ,
       0.        , 0.07713625, 0.07657551, 0.        , 0.        ,
       0.        , 0.        , 0.0758488 , 0.        , 0.        ,
       0.        , 0.06794107, 0.        , 0.        , 0.        ,
       0.        , 0.08233374, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06906824,
       0.        , 0.        , 0.07861449, 0.        , 0.07512828,
       0.        , 0.07167001, 0.        , 0.        , 0.        ,
       0.07158697, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07752431, 0.        , 0.        ,
       0.0723586 , 0.        , 0.        , 0.        , 0.07659323,
       0.        , 0.        , 0.        , 0.        , 0.0727692 ,
       0.08751248, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0875836 , 0.07658321,
       0.        , 0.        , 0.        , 0.        , 0.07228304,
       0.        , 0.07218058, 0.07491696, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07218058, 0.07195802,
       0.        , 0.07915127, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08219232, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07490861, 0.        , 0.07097731, 0.07610564, 0.        ,
       0.        , 0.07712377, 0.        , 0.08866744, 0.        ,
       0.        , 0.08050373, 0.        , 0.        , 0.        ,
       0.        , 0.06816926, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06971676, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07239926, 0.        , 0.07243171, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07660161, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07936987,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06947885,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07560939, 0.        ,
       0.        , 0.        , 0.0823663 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07315653, 0.        , 0.        , 0.        ,
       0.        , 0.075865  , 0.        , 0.07123061, 0.07332923,
       0.        , 0.06891355, 0.        , 0.        , 0.        ,
       0.        , 0.07239926, 0.        , 0.        , 0.43912252,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

When user give the domain as per his requirements this function wil recommend him persons eligble for the post on the basis of the experince and number of projects.

In [93]:


def recommendation(domain, data, matrix, similarity):
   
    if domain not in data['Area_of_Interest_1'].values:
        print(f"Domain '{domain}' not found in the dataset.")
        return
    domain_data = data[data['Area_of_Interest_1'] == domain]

    domain_indices = domain_data.index
    idx = domain_indices[0]
    similarity_scores = similarity[idx]
    similar_indices = np.argsort(similarity_scores)[::-1] 

    for i in similar_indices:
        recommended_employee_name = data.loc[i, 'Ename']
        print(recommended_employee_name)

## Recommendation for the given input

Example user fill Domain ML

In [94]:
recommendation("ML", data, matrix, similarity)

Teresa Munoz
John Short
Huey Hill
Robert Harrison
John Stevens
Jose Clark
Melissa Apodaca
Karen Leonard
Beth Short
Lillian Rork
Christine Geronimo
Jason Oneal
Alycia Green
Kum Ashcraft
Julius Latus
James Williams
James Smith
Ruby Davis
Melinda Johnson
Patricia Parks
Kenneth Tuten
Gary Jones
Ronald Brown
Michael Graham
Jose Durrant
Denise Allen
Robert Good
Carl Brown
George Hill
Vincent Deininger
Heather Martinez
John Pina
Thomas Nelson
John Bennett
John Priest
Paul Moore
Michael Anderman
Mary Vaughan
Rikki Felix
Michael Slaton
Deborah Williams
Henry Williams
Charles Bravo
Wayne Johnson
Michael Sisk
Charles Hajek
Charles Merriweather
Charles Masker
James Juarez
James Sachs
Marjorie George
Shane Jones
Erick Shaw
Indira Broaddus
Karissa Taylor
Wade Gass
Johnnie Gomez
Charles Daniels
Mary Martins
William Houghton
Jerry Raymond
Martha Robinson
Julie Mitchell
Charlie Smith
George Carbaugh
Jennifer Villela
Beatriz Lee
Danielle Powell
Patricia Bourgeois
Felix Lewis
Sandra Mosher
Jerry Unruh
Jerry Thorn
Joseph Gunderson
Laura Bosco
Kathleen Bambacigno
Brian Sparks
Daniel Somers
Ronald Heberling
Maria Sikes
Eric Kouba
Susan Weber
Kathleen Yazzie
Carl Matsuno
Carl Heyde
Christopher Shultz
Tonya Nelson
Sandra Cottingham
Gary Blake
Donald Ruybal
Stanley Hooks
Beverly Klein
Cathy Small
Cornelia Gutierrez
Wallace Crowell
Maria Malone
Larry Reifsteck
Kathy Cook
Dorene Moore
Bonnie Clark
Jesusita Adams
Ileana Adams
Edward Joyce
Andre Hughes
Christopher Farnam
Kathy Price
Brittany Vario
Floyd Mateo
Zachary Harrell
Brian Devine
Willie Fuoco
Johnny Campbell
Kevin Jablonski
Esther Floyd
Reginald Robinson
Marie Cherry
Diane Daughtry
Tommy Buchanan
Mark Odell
Vincent Hatley
Nancy Knight
Anna Chavez
Everett Tatom
Jonathan Cochran
Deborah Coles
Clara Herring
Minnie Rubin
Bernice Goldson
Lara Stancil
Kimberly Deen
Elsie Cucco
Edith Pacheco
Joan Mejia
Joan Swenson
Roger Pigeon
Tamara Wright
Pedro Clinton
Corinne Slinkard
Patrick Constantini
Eva Mccombs
Nichole Jantz
Rogelio Singletary
Gwendolyn Barrow
Candace Odum
Betty Yang
Jan Rothwell
China Lebovic
Petra Gaskin
Shelia Mead
Stephen Burritt
Holly Barrows
Dolores Hickman
Julio Tatom
Rosalyn Garden
Miguel Thrasher
Valerie Lacy
Naomi Risher
Darin Becker
Kyle Knott
Peter Skeeter
Lance Crook
Annie Santana
Craig Girouard
Glenn Bumbrey
Earle Nehring
Berniece Cockrell
Harry Vanhouten
Natasha Wagner
Elias Trimble
Adrian Cooley
Ila Emberling
Helene Schmalz
Ann Marsh
Jeanne Tovar
Rosa Montgomery
Paul Anderson
Neil Elton
Marie Sanchez
Jackie Menges
Debra Rogers
Eric Conrad
Sandie Bautista
Gerald Craft
Kent Travis
Barbara Wollschlager
Mary Rhea
Louis Dupont
George Mitchell
Kerri White
Steven Ramos
Michelle Edgar
Deena York
Sue Cox
Timothy Braziel
Kathryn Gault
Ross Markow
Robert Caroll
Gary Dollard
Dianne White
Jack Deyoung
Barbara Wing
Marie Johnson
Arturo Hemphill
Curtis Milam
William Woods
Ellie Demaio
Randolph Glasgow
Roy Goins
Michael Kruse
Perry Nelson
Michael Rolle
Elsie Coney
James Magallon
Glen Gautreau
Virginia Mcshea
Doris Jean
Cindy Mata
Michael Wells
Catherine Scheller
Gloria Jones
Chad Gamache
Leila Oakes
Cyrus Aragon
Mary Cush
Gary Wallace
Dennis Bisonette
Dora Rainforth
Cynthia Malkin
Rosemary Romero
Jerome Underwood
Nancy Howe
Laura Allen
Elena Cramer
Ashley Hippen
Gary Sanchez
Lucille Lunsford
Nydia Schwing
Donna Farnsworth
Cecilia Islam
Theron Smith
Armando Smith
Dana Alba
Charles Rose
Erin Bade
Stephan Perez
Linda Richardson
Marie Whitt
Theron Nelson
Vivian Carver
Zachary Hafenstein
Amanda Stollings
Helen Simpson
Lucille Tousom
Jennifer Garcia
Rose Brady
Susan Spears
Rena Price
John Fitzgerald
Leon Kramer
Shannon Mcintosh
Lisa Mondragon
Raul Knox
Betty Rodriguez
Joseph Marcum
Frances Mackenzie
Janis Strickland
Robert Rezac
Anna Crays
Ronald Gaughan
Mary Gunning
Kera Cook
Carol Keller
Dominick Mckenzie
Frederick Davey
Melissa Chean
John Hance
Cathy Carns
Kathleen Wheeler
Rosella Perze
Charles Amaya
David Williams
Peggy Clark
Paul Mack
Peggy Luna
Joshua Sand
Lori Spurlock
Katie Barton
Courtney Whelan
Michael Craddock
Brain Moe
Juan Aragon
William Grenier
Bruce Arnold
Joseph Stone
Steven Buck
Robbie Dew
Gilbert Hudnall
Elaine Aliaga
Holly Wakefield
Barbara Pritt
Sonia Anderson
Sarah Young
Alaine Rehberg
Miriam Levan
Martha Wilson
Beatriz Bruss
Joseph Pribble
Stacey Mcginty
Pamela Scruggs
Willie Johnson
Jessica Tiffany
June Gehring
Katie Pena
Lawrence Armstrong
Laura Reynolds
Faith Ramirez
Harold Friedman
Reynaldo Hart
Eleanor Davis
Casey Mcintyre
Martin Rosado
Johnetta Cheung
Jason Burden
Emilio Marra
Patricia Dudley
Janice Foster
Santos Goode
Anita Harrelson
Robert Clodfelter
Bobby Horner
Philip Capozzoli
Barrie Cosgrove
William Wolf
Jerry Parkinson
Dominick Cruz
William Hawkins
Sarah Burkley
Candace Robinson
Kathryn Cottrell
Kenneth Heyne
Nancy Jackson
Rebecca Marlow
Judy Minton
Patrick Scavone
Diane Williams
Melissa Cruz
Lloyd Lahay
Alan Duncan
Marion Hicks
Carol Defabio
Antonio Mcclanan
Marianne Welsh
Cathy Brown
Robert Saddler
Bruce Ellis
Brandon Wainwright
Charles Braxton
Sarah Wilson
Brittany Cody
Kimberly Lozano
Debbie Pulver
Michael Flatt
Marcy Martin
Johnna Haag
Andrea Christensen
Melvin Gutierrez
David Rankin
Linda Leung
Floyd Fernandez
Violet Fisher
Leo Pagan
Norma Lewis
Erika Brown
Mary Page
Iris Meier
Francis Pounds
Douglas Harrington
Sue Bonn
Anthony Roe
Ben Osler
Eric Keister
Scott Alexander
Suzanne Devoe
Paul Ortiz
Timothy Mcpherson
Tabatha Pena
John Campos
Jeffery Parikh
Sandra Matthews
Corinne Burnley
Roberta Barnes
John Trout
Alan Denny
Patricia Shepherd
Michael Harpole
Lawrence Litzenberg
John Peters
Charles Vine
Shannon Campo
Shirley Mcmahon
Tarsha Caines
Robert Wilson
Rachel Morse
Shannon Berryhill
Kennith Hamilton
William Berger
Bernice Bousquet
Nicolas Fulcher
Mary Todd
Jennifer Fortner
Annette Dipietro
Jesus Hampton
Digna Williams
Anna Carmona
Norma Runyan
Elsie Holman
Sallie Jennings
Linda Reck
Clare Stockton
Lisa Green
Yvonne Caron
Gertrude Curtis
Leroy Smith
Esperanza Galletti
Samantha Vasquez
Melissa Montoya
Barbara Amick
Melody Jones
James Copper
Donna Garza
Alice Jordan
Danielle Farmer
Kathryn Ehrhart
Maria Williamson
Felicia Lampe
Larry Barton
Jose Buresh
Joseph Parsons
Tony Hefferon
Jean Blow
John Lebarron
Barbara Washington
Nicholas Rondeau
Sandra Byrd
Mary Jones
Jerry Brown
Rita Ohmen
Benjamin Wilcoxen
Tony Yoakum
Karen Wood
Jovita Golden
Cynthia Contreras
Christine Lara
Celeste Cunningham
Basil Welker
Latonya Bradley
Julia Stanley
Danielle Keister
Kathryn Shultz
Antonio Steffan
Sharyn Brown
Laura Canon
Christopher Ross
Linda Sharp
Jeffery Delisio
Ashley Lindsay
Gale Newell
Tanya Bishop
Karen Ramsey
Melissa Ramirez
Robert Conover
Harvey Mclain
Leon Redd
Gladys Sloan
Ruby Bunch
Rita Sawyer
Rachel Hunsberger
Maurice Anderson
Oliver Lark
Robert Vallejo
Susan Brown
Paul Gray
John Davis
George Thomas
Beth Ebert
Dixie Medina
Anthony Mooney
Robert Kelsey
Ronald Smith
Kay Thomas
Gregory Pickett
Sharon Evans
Paul Kennon
Margaret Wilhelm
Johnny Garcia
Latanya Brooks
Michele Garguilo
Theron Degennaro
Yolanda Kramer
Stacia Aita
Reuben Sparks
Cora Jones
Hope Hicks
Beryl Rogers
Jeromy Muriel
Earl Wood
John Ervin
Cecilia Dale
Jeff Applebee
William Champion
Jessica Montgomery
Estelle Lamm
Lucy Montoya
Rose Kelly
Louise Woody
Donna Morgia
Brian Vaughan
Clyde Young
Tami Williams
Jennifer Collins
Daniel Roberge
Tiffany Secrest
Tracy Houston
David Berry
Willis Ingram
Justin Scott
Melissa Hernandez
Sam Sanchez
Amy Meyer
Robin West
Mable Billiot
Larry Jopling
Thomas Torres
Rita Sackett
Christina Cable
Marilyn Dec
Benny Mendoza
Freda Vega
Raymond Volesky
Dan Christian
Carmen Brock
Edward Gonzalez
Susan Carrillo
Larry Jensen
Donna Goddard
Scott Brown
Daniel Arvizu
Jacob Crouch
Bobby Fields
Mike Blaize
Robert Woodberry
Patricia Bonn
Michael Ferguson
William Vargas
Kenneth Mcclaine
Bruce Stuart
Lillian Mayer
David Dipiano
Kathleen English
Helen Murdock
Garry Pollard
Charlotte Wortham
Mary Laswell
Christopher Timbers
Pam Hicks
Barbara Jeter
Jimmie Williams
Charles Vandergriff
Travis Amos
Christian Tederous
Mamie Threlkeld
Sophia Massiah
Heather Kovach
Johnny Middleton
Michael Joseph
Lucy Kight
Norman Cannon
William Mackey
Albert Coble
Donald Cole
Beverly Oconnor
Tonya Stroth
Tony Gray
Pamela Keener
Don Walker
Kathleen Dyches
Dwain Karalis
Dong Moss
Fred Lashua
Dustin Simmons
Chris Short
Alma Martin
Rosemary Hughes
Rebecca Barrett
Joseph Huslander
Anthony Baker
John Hughes
Jared Powell
Frank Aurand
Lawrence Burns
Elena Sheets
Ruth Jiron
Vickie Parker
Ida Cooper
Karen Smith
Chris Mchugh
Michael Avila
Justin Davis
Linda Bales
Ralph Harris
David Moore
Richard Vanicek
Edwin Feldkamp
Paul Hicks
Larry Gibson
Allen Hawkins
Raymond Rivera
Gilbert Rowden
Simon Chapman
Nick William
Charles Connelly
Esther Witherspoon
Annette Oflaherty
David Hyneman
Susan Lassiter
Wayne Brandenberger
Rubin Centini
Joni Eakin
Linda Zane
Michael Harrison
Mabel Duane
Sandra Onks
Roxanne Furr
Katherine Cornell
Walter Couch
Duane Grant
Doreen Mcentyre
Tim Miller
Maxine Person
Billie Lee
Maryann Simmons
Alison Marti
Carl Granger
Cynthia Williams
Elvis Elliam
Connie Hayes
Steve Good
Gary Lilly
Christy Delarosa
Edna Atwell
Sean Virgilio
Christian Medina
Sarah Gohn
Leo Nest
Sarah Coates
Daniel Cast
Kevin Cocks
James Stamdifer
Josephine Johnson
Jaime Manjarrez
Shaun Vanhook
Henry Wheeler
Daniel Godsey
Sarah Wake
Eddie Wester
George Slayton
Thomas Davis
Margaret Sims
Nina Reed
June Stoneking
Wanda Thao
George Shannon
Thomas Martin
Robert Nikas
Micheal Shupe
Scott Pride
Aaron Donahoe
Carl Chien
Christine Warner
Lorrine Granger
Charles Parker
Margarita Noll
James Herndon
Michael Plateroti
Patricia Lesher
Mitchell Yeldell
Donald Dean
Chance Knox
Nicole Wilson
Stacey Hayes
Ofelia Cayea
Richard Tomlin
Armando Brown
Jose Bond
Constance Rozier
Trista Cheek
Nicole Meeks
Joseph Buckner
Virginia Hamby
Joan Takemura
Ricky Hood
Angelo Houck
Thomas Barton
William Nelson
Russell Collyer
John Gerrald
Meredith Flores
Sylvia Thigpen
Cynthia Anaya
Peter Dellinger
Mae Hill
William Williamson
Tara Lyons
Adeline Roberts
Jonathan Zingaro
Bryan Chase
John Davisson
Barbara Pang
Cyrus Pollack
Kenneth Bolton
Sandra Rosas
Geoffrey Maulden
Franklin Larkin
Jake Dunn
Sarah Jones
Michael Bonds
Manual Isaac
Ramona Kenney
Juanita Morales
Jessica Harp
Keith Chavis
Paris Michalik
Chester Sigler
Teodoro Butler
Karen Baichan
Tabatha Ward
George Ramirez
Frank Vasquez
Boyd Smith
John Lopez
Eugene Caputo
David Esquivel
Francisco German
Scott Meeks
Nina Stuzman
Jo Aiken
Damaris Velazquez
Roger Newland
Son Phillips
Michael Miles
Duane Rodriguez
Robert Hooper
Fran Worthington
Richard Trudnowski
Lauren Pawloski
Sherryl Carey
Ralph Jackson
Enrique Wakefield
Lynn Ottesen
Gail Chesser
Ryan Cahill
Daniel Cody
Dennis Butler
Francisco Morris
Christina Chavis
Terri Hooks
Nancy Hetrick
George Butler
Jeffery Mccalla
James Layton
Edith Schmidt
Willie Deloach
Eva Notti
Carrie Stephens
Maureen Johnson
Dina Mahoney
Joe Ballard
David Butler
Esperanza Urreta
Jean Smith
Margaret Crowder
Gene Latimer
Jane Truong
Elizabeth Kelly
Luke Strause
Lloyd Baker
Steven Manley
Mary Palomo
Hazel Stanley
Ericka Burke
Laura Pouncey
Scott Billings
Angelina Scerra
Terry Laughlin
Charlotte Suarez
Doyle Werts
David Owens
Maureen Craddock
Diane Gregory
Angie Eberts
Yoshiko Mcdonald
Edward Samons
Leslie Johnson
Saundra Rodriguez
Freda Bass
Crystal Olvera
Derrick Carter
Ray Scarnati
David Lowry
Margaret Miller
Norman Jones
Allen Peterson
Brooke Rounds
Sharon Scerbo
Anita Pearsall
Darrell Desjardins
Elsa Gilliland
Betsy Jackson
Larry Harris
Kenneth Frey
Robert Clark
Anthony Ludlow
Bill Sukhu
Jennifer Moore
Lindsay Jobe
Kristina Townley
Julie Flaherty
Barbara Bell
Zachary Murphy
Mildred Beaudette
Grace Perigo
Rakesh Raj
Dolores Lee
Clara Benoist
Patricia Lewis
Terresa Wright
Celia Jackson
James Mcgee
Kenneth Crossman
Jeffrey Denny
Bryan Hanson
James Bevan
Thomas Salazar
Jimmie Johnston
Tina Villalta
Robert Martin
Rosa Bongiorno
Patricia Dominguez
John Gutierrez
Maria Deese
Adele Garren
Rose Bailey
Linda Nunmaker
William Buchanan
Arnold Witaszek
Nicholas Durbin
Heather Gonzalez
Jennifer Wood
Norma Symes
Jack Coffin
Phyllis Dekany
Lori Adams
Melody Best
Anna Bell
Larry Rodriguez
David Edmonds
Ronnie Modi
Dorothy Kenimer
Orlando Schuld
Sara Hernandez
Jerry Baier
Jonathan Cropper
Tiffany Franklin
Elizabeth Bannister
Blanche Debaecke
Melvin Romero
Dustin Harris
Sherry Landers
Norene Mcfadden
Carol Tretheway
Karie Keenan
Eric Woodall
Gary Tabron
Cammie Farris
Jimmy Klein
Erin Quarles
Ruth Murray
Maria Blevins
Jenny Baxter
Sarah Marshall
Gina Auten
Robert Simon
David Whitaker
Elizabeth Caldwell
William Wojenski
Helen Johnson
Staci Beach
Joe Harris
Lucy Machen
Deann Schmidt
Milton Quigley
Charles Reid
Lynne Yanez
Peter Ozuna
Doris Alverez
Robert Lieberman
Joseph Frey
Carlos Verdin
Jesus Cameron
Tony Webb
Jack Magana
Rose Kirkland
Bryan Staples
Jason Salas
James White
Eric Smith
Stephen Ross
Marshall Russell
Dana Amin
Russell Bacon
Alexander Fitzsimmons
George Prosser
John Gonzalez
Brendon Irvine
Royce Bowers
Pedro Mcginnis
Christopher Stuckey
Catherine Ellis
Linda Crawford
Rita Miller
Viola Montoya
Alberta Fanter
Katelyn Pearson
Elizabeth Yeend
Brandon Wallace
Margaret Mettler
Lillian Masom
Ricky Lee
Brian Best
Brittany Thompkins
James Medlock
Andrew Lehman
Jennifer Robinson
Mary Mcclain
Jeff Porter
William Britt
Joe Ponce
Shawn Shackelford
Marie Mitchell
Stephanie Rosenzweig
Waldo Sanchez
John Boisen
Annette Watson
Manuel Jamison
Jessica Clark
Dana Stout
Rolando Jones
Kevin Gonzales
Jamal Kelley
William Jeter
Michael Everson
Betty Wood
Eunice Mullen
Ruby Peters
Mario Crafton
Elliot Parenteau
Violet Vincent
Jessica Mitchell
Renee Jackson
Mark Tacadina
Dale Hardy
Karen Sumler
Sylvia Eubanks
Charles Johnson
Courtney Bergeron
Dorothy Rodriguez
Evelyn Wallick
Sarah Cacioppo
James Keys
Jeffrey Siddoway
Charles Hilde
Lillian Walker
Donald Carrier
Amanda Marble
Deann Jefferies
Clifford Boyd
Diana Burchett
Gregory Nichols
David Abraham
Elizabeth Morreale
Michael Young
Patrick Biddle
Shelby Hillery
Ronald Milar
Terrell Timme
James Cacy
Allison Patten
Bennie Coffey
Alexander Graham
Dana Bond